close all; clear; clc;

script_dir = fileparts(mfilename('fullpath'));
data = readtable(fullfile(script_dir, 'fitted_values.csv'), 'TextType', 'string');

axial = sortrows(data(data.measurement_direction == "axial", :), ...
    'plot_order');
radial = sortrows(data(data.measurement_direction == "radial", :), ...
    'plot_order');

axial_strain = (axial.d_spacing_angstrom - axial.d0_angstrom) ...
    ./ axial.d0_angstrom * 1e6;
radial_strain = (radial.d_spacing_angstrom - radial.d0_angstrom) ...
    ./ radial.d0_angstrom * 1e6;
axial_uncertainty = sqrt( ...
    (axial.d_spacing_uncertainty_angstrom ./ axial.d0_angstrom).^2 + ...
    (axial.d_spacing_angstrom .* axial.d0_uncertainty_angstrom ...
    ./ axial.d0_angstrom.^2).^2) * 1e6;
radial_uncertainty = sqrt( ...
    (radial.d_spacing_uncertainty_angstrom ./ radial.d0_angstrom).^2 + ...
    (radial.d_spacing_angstrom .* radial.d0_uncertainty_angstrom ...
    ./ radial.d0_angstrom.^2).^2) * 1e6;

poisson_ratio = 0.28;
expected_radial_strain = -poisson_ratio .* axial_strain;
expected_radial_uncertainty = poisson_ratio .* axial_uncertainty;

lower_bound = expected_radial_strain - expected_radial_uncertainty;
upper_bound = expected_radial_strain + expected_radial_uncertainty;
x = axial.instrument_position_mm;
x_fill = [x; flipud(x)];
y_fill = [upper_bound; flipud(lower_bound)];

figure;
plot(radial.instrument_position_mm, radial_strain, ...
    'Color', [0.337, 0.7059, 0.9137], 'LineStyle', '-', ...
    'Marker', 'diamond', 'MarkerSize', 5, 'LineWidth', 1, ...
    'DisplayName', 'Measured \epsilon_{rr}');
hold on;
plot(x, expected_radial_strain, ...
    'Color', [0.85, 0.33, 0.10], 'LineStyle', '--', ...
    'Marker', 'diamond', 'MarkerSize', 5, 'LineWidth', 1, ...
    'DisplayName', 'Expected \epsilon_{rr} under uniaxial stress');
errorbar(radial.instrument_position_mm, radial_strain, radial_uncertainty, ...
    'Color', [0.337, 0.7059, 0.9137], 'LineStyle', 'none', ...
    'LineWidth', 0.5, 'CapSize', 3, 'HandleVisibility', 'off');
errorbar(x, expected_radial_strain, expected_radial_uncertainty, ...
    'Color', [0.85, 0.33, 0.10], 'LineStyle', 'none', ...
    'LineWidth', 0.5, 'CapSize', 3, 'HandleVisibility', 'off');
fill(x_fill, y_fill, [0.6, 0.6, 0.6], ...
    'FaceAlpha', 0.15, 'EdgeColor', 'none', 'HandleVisibility', 'off');

set(gca, 'XDir', 'reverse', 'TickDir', 'out', 'Box', 'off', ...
    'FontSize', 6, 'FontName', 'Arial', 'LineWidth', 0.5);
xticks(flip(x));
xticklabels(flip(round(x(1) - x)));
ylim([-350, 550]);
yticks(-350:50:550);
y_labels = strings(size(-350:50:550));
y_labels(1:2:end) = -350:100:550;
yticklabels(y_labels);
xlabel('Distance from the tip of the wire (mm)', ...
    'FontSize', 7, 'FontName', 'Arial');
ylabel('Microstrain (\mu\epsilon)', 'FontSize', 7, 'FontName', 'Arial');
legend('Location', 'northwest', 'Box', 'off', ...
    'FontSize', 7, 'FontName', 'Arial');
set(gca, 'LooseInset', get(gca, 'TightInset'));
set(gcf, 'Units', 'inches', 'Position', [5, 5, 3.85, 3.0]);
